worker_processes auto;
events {
  worker_connections 1024;
}

rtmp {
    buflen 3s;
    server {
        listen 1919;
        listen [::]:1919 ipv6only=on;
        chunk_size 4096;

        application live {
            live on;
            meta on;
            interleave on;
            max_connections 150;

            session_relay on;

            # HLS settings
            hls on;
            hls_path /tmp/hls;
            hls_fragment 10s;
            hls_playlist_length 1m;

            # Video recording
            record all;
            record_path record;
            record_unique on;
            record_max_size 0;
            record_suffix .flv;
            record_interval 3m;      ## Local
            # record_interval 90m;   ## Live
            record_notify on;

            # Stream callbacks (optional)
            ## LOCAL
            on_publish http://44.216.74.109/livestream/local/start.php;
            on_publish_done http://44.216.74.109/livestream/local/stop.php;
            on_record_done http://44.216.74.109/livestream/local/record.php;

            ## LIVE
            # on_publish http://44.216.74.109/livestream/frontend/public/api/stream/start;
            # on_publish_done http://44.216.74.109/livestream/frontend/public/api/stream/stop;
            # on_record_done http://44.216.74.109/livestream/frontend/public/api/stream/record;
    
            # on_record_done event
            exec_record_done /timeout.sh $name;
        }
    }
}

http {
    # 
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    # 
    tcp_nodelay on;
    server {
        listen 8989;

        location / {
            root /www;
        }

        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                application/octet-stream ts;
            }
            root /tmp;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        location /log {
            proxy_pass http://44.216.74.109/livestream/local/stream.log;                    ## Local
            # proxy_pass http://44.216.74.109/livestream/frontend/public/log/stream.log;    ## Live
        }
    }
}
