version: "3.9"
services:
  [SERVER_NAME]:
    image: shared-rtmp-image
    container_name: [CONTAINER_NAME]
    ports:
      - "[RTMP_PORT]:[RTMP_PORT]"
      - "[HTTP_PORT]:[HTTP_PORT]"
    environment:
      - RTMP_PORT=[RTMP_PORT]
      - HTTP_PORT=[HTTP_PORT]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/www/index.html
      - ./data:/tmp/hls
      - ./record:/record
      - ./timeout.sh:/timeout.sh
    command: /bin/sh -c "nginx -g 'daemon off;'"
    networks:
      - [NETWORK_NAME]
networks:
  [NETWORK_NAME]:
    name: [NETWORK_FIXED_NAME]
    driver: bridge
    external: true